-- Criar remessas de teste usando endereços existentes
INSERT INTO shipments (
  sender_address_id,
  recipient_address_id,
  weight,
  length,
  width,
  height,
  format,
  selected_option,
  pickup_option,
  status,
  tracking_code,
  motorista_id,
  quote_data,
  payment_data
) VALUES 
  (
    (SELECT id FROM addresses LIMIT 1),
    (SELECT id FROM addresses LIMIT 1 OFFSET 1),
    2.5,
    20,
    15,
    10,
    'caixa',
    'express',
    'pickup',
    'PAYMENT_CONFIRMED',
    'TEST01-REMESSA',
    NULL,
    '{"express_price": 25.50, "economic_price": 15.30}'::jsonb,
    '{"status": "paid", "method": "pix"}'::jsonb
  ),
  (
    (SELECT id FROM addresses LIMIT 1),
    (SELECT id FROM addresses LIMIT 1 OFFSET 1),
    1.8,
    30,
    20,
    8,
    'envelope',
    'economic',
    'pickup',
    'PAID',
    'TEST02-REMESSA',
    NULL,
    '{"express_price": 18.90, "economic_price": 12.50}'::jsonb,
    '{"status": "paid", "method": "card"}'::jsonb
  ),
  (
    (SELECT id FROM addresses LIMIT 1),
    (SELECT id FROM addresses LIMIT 1 OFFSET 1),
    3.2,
    25,
    18,
    12,
    'caixa',
    'economic',
    'delivery',
    'PAGO_AGUARDANDO_ETIQUETA',
    'TEST03-REMESSA',
    NULL,
    '{"express_price": 32.40, "economic_price": 22.80}'::jsonb,
    '{"status": "paid", "method": "boleto"}'::jsonb
  );