// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { SessionManager } from '@/utils/sessionManager';

const SUPABASE_URL = "https://dhznyjtisfdxzbnzinab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRoem55anRpc2ZkeHpibnppbmFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MDMyNjAsImV4cCI6MjA3MTk3OTI2MH0.8HFgijn6E2LQSgvP0SQqYA8QDCOoZOqfAC3CMwkf6Co";

// Create enhanced client that includes session headers  
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});