// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhznyjtisfdxzbnzinab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRoem55anRpc2ZkeHpibnppbmFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MDMyNjAsImV4cCI6MjA3MTk3OTI2MH0.8HFgijn6E2LQSgvP0SQqYA8QDCOoZOqfAC3CMwkf6Co";

// Create enhanced client that supports secure session headers  
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      // Session token will be added dynamically when needed
    }
  }
});

/**
 * Create a Supabase client instance with session headers for anonymous users
 */
export function createSecureSupabaseClient() {
  // Get session token from localStorage
  const getSessionToken = () => {
    try {
      const sessionData = localStorage.getItem('confix_secure_session');
      if (sessionData) {
        const parsed = JSON.parse(sessionData);
        return parsed.token;
      }
    } catch (error) {
      console.error('Error getting session token:', error);
    }
    return null;
  };

  const sessionToken = getSessionToken();
  
  if (sessionToken) {
    return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
      global: {
        headers: {
          'x-session-token': sessionToken
        }
      }
    });
  }
  
  return supabase;
}